### ISSUE TITLE
부등호의 가독성

### ISSUE THREAD

**Issue by shinkeonkim** [mingtian-chan/kmu_cpp_programming#1]
https://github.com/mingtian-chan/kmu_cpp_programming/blob/28cda89aea21fc26a6a8dcc95be0360305d31082/c%2B%2B%20%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4/%EB%84%A4%EB%AA%A8%EB%A7%8C%EB%93%A4%EA%B8%B0_3.cpp#L13-L14

아래와 같이 쓰면, 1부터 n까지 폐구간임을 조금이라도 더 빠르게 캐치하면서 다시 검토할 수 있어요!
```cpp
for (int j = 1; j <= n; j++){
```

**Comment by mingtian-chan** [comment]
아 j <= n 까지가 더 가독성이 좋은듯 ㅇㅇㅇㅇ
