### ISSUE TITLE
의미없는 초기화 구문

### ISSUE THREAD

**Issue by shinkeonkim** [mingtian-chan/kmu_cpp_programming#2]
https://github.com/mingtian-chan/kmu_cpp_programming/blob/28cda89aea21fc26a6a8dcc95be0360305d31082/c%2B%2B%20%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4/%EB%91%90%EC%82%AC%EA%B0%81%ED%98%95_%EB%A9%B4%EC%A0%81%EA%B5%AC%ED%95%98%EA%B8%B0.cpp#L30-L31

상단에서 tmpx와 tmpy를 수식으로 초기화하고 있기 때문에 굳이 0으로 다시 할당하는 로직은 없어도 됩니답 😃

**Comment by shinkeonkim** [comment]
그 외 로직은 너무 깔끔하네요. 변수명이 조금 아쉽긴 한데..이건 나중에 구조체 같은거 배우시고 나서 처리하시면 될 것 같아여

**Comment by shinkeonkim** [comment]
저는 주로 Point에 대한 것이 나오면
```cpp
struct Point {
	int y, x;
};
```
부터 만들고 보는 편이에요 ㅋㅋ

**Comment by mingtian-chan** [comment]
아직 struct 문법은 안 배워서 ㅋㅋㅋ 배우면 써먹어야 할듯! 
tmpx 초기화 부분은 빼도 되는구나 땡쓰
