### ISSUE TITLE
[주의] round는 내장함수!

### ISSUE THREAD

**Issue by shinkeonkim** [mingtian-chan/kmu_cpp_programming#3]
https://github.com/mingtian-chan/kmu_cpp_programming/blob/28cda89aea21fc26a6a8dcc95be0360305d31082/c%2B%2B%20%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4/%EB%91%90%EC%82%AC%EA%B0%81%ED%98%95_%EB%A9%B4%EC%A0%81%EA%B5%AC%ED%95%98%EA%B8%B0.cpp#L28

round는 [C++ 내장 함수](https://en.cppreference.com/w/cpp/numeric/math/round)에요. 변수명으로 쓰실때 주의하셔야 합니다

**Comment by mingtian-chan** [comment]
아아아 맞네 그렇구나 저렇게 변수로 쓰면 함수로는 못 쓰게 되는거지?

**Comment by shinkeonkim** [comment]
네네 근데 또 round라는 변수가 선언되어있지 않는 다른 함수에서 호출하면, 내장함수로 인식할 거라서 헷갈릴 수 있어요

**Comment by mingtian-chan** [comment]
옥께!
