### ISSUE TITLE
[질문] | 숏코딩을 의도하신 건가요?!

### ISSUE THREAD

**Issue by shinkeonkim** [mingtian-chan/kmu_cpp_programming#4]
https://github.com/mingtian-chan/kmu_cpp_programming/blob/28cda89aea21fc26a6a8dcc95be0360305d31082/c%2B%2B%20%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4/%EB%91%90%20%EA%B5%AC%EA%B0%84(interval)%EC%9D%B4%20%EC%B0%A8%EC%A7%80%ED%95%98%EB%8A%94%20%EA%B8%B8%EC%9D%B4%20%EA%B5%AC%ED%95%98%EA%B8%B0%20.cpp#L10-L16

해당 조건들이 모두 bool 타입으로 나와서 비트 OR로 해도 똑같으니 로직에 영향을 안줬네요 ㅋㅋ 

다른 사람과 같이 짜고 있는 상황이라면 `||`이 더 잘 이해되지 않았을까 해여

**Comment by mingtian-chan** [comment]
앗,, 의도는 아니었어! ||랑 | 랑 헷갈렸나보네, 비트 OR 문법이랑 || 문법이랑 차이가 있어?

**Comment by shinkeonkim** [comment]
![image](https://user-images.githubusercontent.com/47373998/163700805-7947761e-1788-4598-9f9e-369923e7b8ac.png)

**Comment by shinkeonkim** [comment]
도춣되는 결과와 타입이 달라요

|| 는 bool
| 는 연산에 들어간 변수의 type

**Comment by mingtian-chan** [comment]
(-1 || 0 )에서 -1 은 0이 아니니까, 논리적으로는 true인거? 그래서 0이랑 || 연산 했을 때 true가 나온거야?

**Comment by shinkeonkim** [comment]
넹

**Comment by mingtian-chan** [comment]
bit or 은 어떻게 계산되는거? bit true 는 어떻게 판단해 ? 1111일때?

**Comment by mingtian-chan** [comment]
bit or 은 0011 이랑 1000이랑 계산하면 1011을 리턴하잖아 그거랑 true랑은 어떻게 판단하는거?

**Comment by mingtian-chan** [comment]
완료
